# Generated by Django 5.2.2 on 2025-06-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobbies',
            old_name='Hobbies_desc',
            new_name='hobbies_desc',
        ),
    ]
