# Generated by Django 5.2.2 on 2025-06-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioDB', '0002_rename_hobbies_desc_hobbies_hobbies_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hobbies',
            new_name='Hobby',
        ),
        migrations.RenameField(
            model_name='hobby',
            old_name='hobbies_desc',
            new_name='hobby_desc',
        ),
    ]
