# Generated by Django 5.2.2 on 2025-06-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioDB', '0003_rename_hobbies_hobby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, default='https://www.shutterstock.com/image-vector/default-ui-image-placeholder-wireframes-600nw-1037719192.jpg', null=True, upload_to='portfolioDB/images/'),
        ),
    ]
