# Generated by Django 5.2.2 on 2025-06-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioDB', '0004_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.CharField(default='https://cdn-icons-png.flaticon.com/512/135/135161.png', max_length=600),
        ),
    ]
