# Generated by Django 5.2.2 on 2025-06-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioDB', '0005_alter_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='image',
            field=models.CharField(default='https://cdn-icons-png.flaticon.com/512/135/135161.png', max_length=600),
        ),
    ]
